rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),

    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category,
        name='show_category'),

    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page,
        name='add_page'),

    #url(r'^register/$',
    #    views.register,
    #    name='register'),

    #url(r'^login/$', views.user_login, name='login'),

    url(r'^restricted/', views.restricted, name='restricted'),

    #url(r'^logout/$', views.user_logout, name='logout'),

]

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView


# Create a new class that redirects the user to the index page,
# if successful at logging
class MyRegistrationView(RegistrationView):

    def get_success_url(self, user):
        return '/rango/'

urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^rango/', include('rango.urls')),
                  # above maps any URLs starting
                  # with rango/ to be handled by
                  # the rango application
                  url(r'^admin/', admin.site.urls),

                  url(r'^accounts/register/$',
                      MyRegistrationView.as_view(),
                      name='registration_register'),

                  url(r'^accounts/password/$',
                      MyRegistrationView.as_view(),
                      name='registration_register'),

                  url(r'^accounts/',
                      include('registration.backends.simple.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):  # For Python 2, use __unicode__ too
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):  # For Python 2, use __unicode__ too
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    # Remember if you use Python 2.7.x, define __unicode__ too!
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime


# Import the Category model
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                                'last_visit',
                                                str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        #update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        # set the last visit cookie
        request.session['last_visit'] = last_visit_cookie
    # Update/set the visits cookie
    request.session['visits'] = visits

def index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    print(request.session['visits'])
    response = render(request, 'rango/index.html', context=context_dict)
    return response


def about(request):
    #if request.session.test_cookie_worked():
    #    print("TEST COOKIE WORKED!")
    #request.session.delete_test_cookie()
    visitor_cookie_handler(request)
    context_dict = {'visits' : request.session['visits']}

    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage is the same as {{ boldmessage }} in the template!
    #context_dict = {'boldmessage': "This tutorial has been put together by Frances."}

    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    #return render(request, 'rango/about.html', context=context_dict)

    # prints out whether the method is a GET or a POST
    #print(request.method)
    # prints out the user name, if no one is logged in it prints `AnonymousUser`
    #print(request.user)
    return render(request, 'rango/about.html',context=context_dict)


def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    #  to the template rendering engine.
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all of the associated pages.
        # Note that filter() will return a list of page objects or an empty list
        pages = Page.objects.filter(category=category)

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category

    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None

    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)
            # Now that the category is saved
            # We could give a confirmation message
            # But since the most recent category added is on the index page
            # Then we can direct the user back to the index page.

            return index(request)
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)

    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
            return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form':form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

"""
def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            #put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

# Render the template depending on the context.
    return render(request,
                  'rango/register.html',
                {'user_form': user_form,
                    'profile_form': profile_form,
                    'registered': registered})
"""

"""
def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # An inactive account was used - no logging in!

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}



{% block body_block %}


    <div>
        here is the about page. <br />
        <strong>{{ boldmessage }}</strong><br />
    </div>

    <div>
        <img src="{% static "images/rango2.jpg" %}" alt="Picture of Rango" />
        <img src="{{ MEDIA_URL}}cat.jpg" />

    <p> visits: {{ visits }}</p>
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load bootstrap_toolkit %}

{% block title_block %}Add Category{% endblock %}

{% block body_block %}

<form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
    <h2 class="form-signin-heading"> Add a new category</h2>

    {% csrf_token %}
    {{ form|as_bootstrap }}

    <button class="btn btn-primary" type="submit" name="submit">
        Add Category
    </button>
</form>


{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}

{% block body_block %}
{% if category %}
<form role="form" id="page_form" method="post"
      action="/rango/category/{{category.slug}}/add_page/">
    <h2 class="form-signin-heading"> Add a Page to
        <a href="/rango/category/{{category.slug}}/">
            {{ category.name }}</a></h2>
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}<br/>
    {{ field }}<br/>
    {% endfor %}
    <br/>
    <button class="btn btn-primary"
            type="submit" name="submit">
        Add Page
    </button>
</form>
{% else %}
<p>This is category does not exist.</p>
{% endif %}
{% endblock %}

templates/rango/base.html
{% extends 'rango/base_bootstrap.html' %}

templates/rango/base_bootstrap.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load rango_template_tags %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">

    <title> Rango -
        {% block title %}
        How to Tango with Django!
        {% endblock %}
    </title>

    {% block side_block %}

    {% endblock %}

    <!-- Bootstrap core CSS -->
    <link href=" http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse"
            data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Rango</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'rango:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:about' %}">About</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:restricted' %}">Restricted Page</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_password_change' %}">Password</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">Sign In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
            {% block sidebar_block %}
            {% get_category_list category %}
            {% endblock %}


        </nav>

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">


            {% block body_block %}

            {% endblock %}

        </main>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous"></script>
<script>
    window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}

    <div>Here is the category page.</div>

    {% if category %}
        <h1>{{ category.name }}</h1>

        {% if pages %}
            <ul>
                {% for page in pages %}

                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>

                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}




          {% if user.is_authenticated %}
              <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
          {% endif %}

    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/cats.html
<ul class="nav nav-pills flex-column">
    {% if cats %}
       {% for c in cats %}
           {% if c == act_cat %}
               <li class="nav-item">
                   <strong><a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong>
               </li>
           {% else %}
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
           {% endif %}
       {% endfor %}
        {% else %}
		<li> <strong>There are no category present.</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Index
{% endblock %}
{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Rango says...</h1>
    {% if user.is_authenticated %}
    <h1>hey there {{ user.username }}!</h1>
    {% else %}
    <h1>hey there partner! </h1>
    {% endif %}
</div>
<div class="row marketing">
    <div class="col-lg-6">
        <h4>Most Liked Categories</h4>
        <p>
            {% if categories %}
        <ul class="list-group">
            {% for category in categories %}
            <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">
                {{ category.name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
        </p>
    </div>
    <div class="col-lg-6">
        <h4>Most Viewed Pages</h4>
        <p>
            {% if pages %}
        <ul class="list-group">
            {% for page in pages %}
            <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
        </p>
    </div>
</div>
<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
<p> visits: {{ visits }}</p>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/oldBase.html
<!-->

<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>

<head>

    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>

</head>

<div>
    {% block sidebar_block %}
        {% get_category_list category %}
    {% endblock %}
</div>

<hr />

<body>

<h1>Rango Says...</h1>

<div>
    {% block body_block %}

    {% endblock %}
</div>

<hr />

<div>
    <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
            <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></l>
            <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            <li><a href="{% url 'auth_password_change' %}">Password</a></li>

        {% else %}
            <li><a href="{% url 'auth_login' %}">Sign In</a></li>
            <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
        {% endif %}

        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>

    </ul>
</div>

</body>
</html>

-->

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>About Page</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}"
              enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted
{% endblock %}

{% block body_block %}

    Since you're logged in, you can see this text!

{% endblock %}